global using HuntTrainAuto.Chat;
global using HuntTrainAuto.Combat;
global using HuntTrainAuto.Contracts;
global using HuntTrainAuto.Domain;
global using HuntTrainAuto.Map;
global using HuntTrainAuto.Movement;
global using HuntTrainAuto.Services;
global using HuntTrainAuto.Teleport;
global using HuntTrainAuto.Windows;
